apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestion-config
  namespace: ingestion
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-kafka-bootstrap.storage.svc.cluster.local:9092"
  INTRADAY_TOPIC: "intraday-data"
  HISTORICAL_TOPIC: "historical-data"
  API_BASE_URL: "http://stock-api.ingestion.svc.cluster.local:8000"
  LOG_LEVEL: "INFO"
  RATE_LIMIT_GLOBAL: "100/minute"
  RATE_LIMIT_PREDICT: "30/minute"
  RATE_LIMIT_INGEST: "10/minute"
  MODEL_FRESHNESS_THRESHOLD_DAYS: "7"
  PREDICTION_STALENESS_HOURS: "24"
  AB_TESTING_ENABLED: "false"
  AB_LOG_ASSIGNMENTS: "true"
  KSERVE_INFERENCE_URL: "http://stock-model-serving-predictor.ml.svc.cluster.local:80"
  KSERVE_MODEL_NAME: "stock-model-serving"
  KSERVE_TIMEOUT_SECONDS: "30"
  KSERVE_ENABLED: "true"
  KSERVE_CANARY_URL: "http://stock-model-serving-canary-predictor.ml.svc.cluster.local:80"
  MINIO_ENDPOINT: "http://minio.storage.svc.cluster.local:9000"
  MINIO_BUCKET_MODELS: "model-artifacts"
  MINIO_SERVING_PREFIX: "serving/active"
  TICKER_SYMBOLS: "AAPL,MSFT,NVDA,AMZN,GOOGL,META,TSLA,BRK-B,AVGO,JPM,LLY,V,UNH,XOM,MA,JNJ,PG,COST,HD,ABBV,MRK,CVX,CRM,BAC,NFLX,PEP,KO,WMT,TMO,CSCO,MCD,ABT,ACN,DHR,TXN,NEE,ADBE,NKE,WFC,PM,ORCL,IBM,RTX,GE,AMD,QCOM,AMGN,HON,INTU,SPGI,LOW,CAT,MS,AMAT,ELV,GILD,DE,BX,ISRG,VRTX,AXP,BKNG,SYK,ADI,PGR,TJX,REGN,CI,ETN,CB,MMC,BDX,EOG,DUK,SO,MO,ZTS,BSX,HCA,MDLZ,GS,CME,AON,SLB,SCHW,PLD,AMT,CCI,PSA,EQIX,WELL,SHW,APD,ECL,ITW,GD,NOC,LMT,MMM,EMR,EW,HUM,MCK,ABC,CVS,WBA,USB,PNC,TFC,COF,AIG,MET,PRU,AFL,ALL,TROW,BLK,NTRS,STT"
