apiVersion: v1
kind: Service
metadata:
  name: stock-api
  namespace: ingestion
  labels:
    app: stock-api
    app.kubernetes.io/part-of: stock-prediction-platform
spec:
  type: ClusterIP
  selector:
    app: stock-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
