apiVersion: v1
kind: Namespace
metadata:
  name: ingestion
  labels:
    app.kubernetes.io/part-of: stock-prediction-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: processing
  labels:
    app.kubernetes.io/part-of: stock-prediction-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    app.kubernetes.io/part-of: stock-prediction-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml
  labels:
    app.kubernetes.io/part-of: stock-prediction-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    app.kubernetes.io/part-of: stock-prediction-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: stock-prediction-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: flink
  labels:
    app.kubernetes.io/part-of: stock-prediction-platform
