apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: storage
  labels:
    app: minio
    app.kubernetes.io/part-of: stock-prediction-platform
    app.kubernetes.io/component: object-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
