apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: storage
  labels:
    app: minio
    app.kubernetes.io/part-of: stock-prediction-platform
data:
  MINIO_ENDPOINT: "http://minio.storage.svc.cluster.local:9000"
  MINIO_BUCKET_MODELS: "model-artifacts"
  MINIO_BUCKET_DRIFT: "drift-logs"
  MINIO_REGION: "us-east-1"
