apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  namespace: flink
  labels:
    app.kubernetes.io/part-of: stock-prediction-platform
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-kafka-bootstrap.storage.svc.cluster.local:9092"
  POSTGRES_HOST: "postgresql.storage.svc.cluster.local"
  POSTGRES_DB: "stockdb"
  POSTGRES_USER: "stockuser"
  FEAST_REPO_PATH: "/opt/feast"
