apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
  namespace: flink
  labels:
    app.kubernetes.io/part-of: stock-prediction-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-role-binding
  labels:
    app.kubernetes.io/part-of: stock-prediction-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: flink
    namespace: flink
