apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: processing
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/tempathack/stock.git
    targetRevision: HEAD
    path: stock-prediction-platform/k8s/processing
  destination:
    server: https://kubernetes.default.svc
    namespace: processing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
